# Generated by Django 4.0.8 on 2023-01-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Name of User')),
                ('name_event', models.CharField(blank=True, max_length=255, verbose_name='Nombre del evento')),
                ('type_event', models.IntegerField(choices=[(None, '(Pendiente)'), (0, 'MIS XV AÑOS'), (1, 'NUESTRA BODA'), (2, 'MI BAUTIZO')])),
                 # codigo añadido
                ('messages', models.TextField(blank=True, verbose_name="Mensajes")),
                 # codigo añadido
                ('date_until_event', models.DateTimeField()),
                ('itinerary', models.ImageField(upload_to='itinerary')),
                ('music', models.FileField(upload_to='music')),
                ('video', models.FileField(upload_to='video')),
                ('excel_invitation', models.FileField(upload_to='excel_invitation')),
                ('video_url', models.URLField()),
                ('carrousel_img_1', models.ImageField(upload_to='invitations_carrousel')),
                ('carrousel_img_2', models.ImageField(upload_to='invitations_carrousel')),
                ('carrousel_img_3', models.ImageField(upload_to='invitations_carrousel')),
                ('carrousel_img_4', models.ImageField(upload_to='invitations_carrousel')),
                ('carrousel_img_5', models.ImageField(upload_to='invitations_carrousel')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ceremony', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('ceremony_when', models.DateTimeField()),
                ('ceremony_map', models.URLField()),
                ('ceremony_image', models.ImageField(upload_to='places')),
                ('ceremony_calendar_google', models.URLField()),
                ('ceremony_calendar_apple', models.FileField(upload_to='calendar')),
                ('ceremony_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('ceremony_lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('reception_address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('reception_when', models.DateTimeField()),
                ('reception_map', models.URLField()),
                ('reception_image', models.ImageField(upload_to='places')),
                ('reception_calendar_google', models.URLField()),
                ('reception_calendar_apple', models.FileField(upload_to='calendar')),
                ('reception_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('reception_lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitations.invitationbase')),
            ],
        ),
        migrations.CreateModel(
            name='GiftTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liverpool_code', models.CharField(blank=True, max_length=10, verbose_name='Liverpool')),
                ('amazon_code', models.CharField(blank=True, max_length=100, verbose_name='Amazon')),
                ('sears_code', models.CharField(blank=True, max_length=12, verbose_name='Sears')),
                ('palacio_de_hierro_code', models.CharField(blank=True, max_length=12, verbose_name='Sears')),
                ('bank_name', models.CharField(blank=True, max_length=12, verbose_name='Banco')),
                ('bank_image', models.ImageField(upload_to='bank')),
                ('bank_account', models.CharField(blank=True, max_length=12, verbose_name='Número de Cuenta')),
                ('bank_account_name', models.CharField(blank=True, max_length=12, verbose_name='Titular de la cuenta')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitations.invitationbase')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(blank=True, max_length=255, verbose_name='Nombre del contacto')),
                ('phone_number', models.CharField(blank=True, max_length=255, verbose_name='Número del contacto')),
                ('default_message', models.CharField(blank=True, max_length=999, verbose_name='Mensaje por defecto')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitations.invitationbase')),
            ],
        ),
    ]
