# Generated by Django 4.0.8 on 2023-01-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttable',
            name='bank_image',
            field=models.ImageField(null=True, upload_to='bank'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='excel_invitation',
            field=models.FileField(null=True, upload_to='excel_invitation'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='music',
            field=models.FileField(null=True, upload_to='music'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='video_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='ceremony_calendar_apple',
            field=models.FileField(null=True, upload_to='calendar'),
        ),
        migrations.AlterField(
            model_name='places',
            name='ceremony_calendar_google',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='ceremony_image',
            field=models.ImageField(null=True, upload_to='places'),
        ),
        migrations.AlterField(
            model_name='places',
            name='ceremony_map',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='reception_calendar_apple',
            field=models.FileField(null=True, upload_to='calendar'),
        ),
        migrations.AlterField(
            model_name='places',
            name='reception_calendar_google',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='reception_map',
            field=models.URLField(null=True),
        ),
    ]
