# Generated by Django 4.0.8 on 2023-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_gifttable_bank_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttable',
            name='bank_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='carrousel_img_1',
            field=models.ImageField(blank=True, upload_to='invitations_carrousel'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='carrousel_img_2',
            field=models.ImageField(blank=True, upload_to='invitations_carrousel'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='carrousel_img_3',
            field=models.ImageField(blank=True, upload_to='invitations_carrousel'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='carrousel_img_4',
            field=models.ImageField(blank=True, upload_to='invitations_carrousel'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='carrousel_img_5',
            field=models.ImageField(blank=True, upload_to='invitations_carrousel'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='excel_invitation',
            field=models.FileField(blank=True, null=True, upload_to='excel_invitation'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='music'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='ceremony_calendar_apple',
            field=models.FileField(blank=True, null=True, upload_to='calendar'),
        ),
        migrations.AlterField(
            model_name='places',
            name='ceremony_calendar_google',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='ceremony_image',
            field=models.ImageField(blank=True, null=True, upload_to='places'),
        ),
        migrations.AlterField(
            model_name='places',
            name='ceremony_map',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='reception_calendar_apple',
            field=models.FileField(blank=True, null=True, upload_to='calendar'),
        ),
        migrations.AlterField(
            model_name='places',
            name='reception_calendar_google',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='reception_image',
            field=models.ImageField(blank=True, upload_to='places'),
        ),
        migrations.AlterField(
            model_name='places',
            name='reception_map',
            field=models.URLField(blank=True, null=True),
        ),
    ]
