# Generated by Django 4.0.8 on 2023-01-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_rename_places_place_alter_invitationbase_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ceremony_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del lugar de la ceremonia'),
        ),
        migrations.AddField(
            model_name='place',
            name='reception_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del lugar de la ceremonia'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_ceremony',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección de la ceremonia'),
        ),
        migrations.AlterField(
            model_name='place',
            name='reception_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección de la recepción'),
        ),
    ]
