# Generated by Django 4.0.8 on 2023-01-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_place_ceremony_name_place_reception_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttable',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titular de la cuenta'),
        ),
        migrations.AlterField(
            model_name='gifttable',
            name='palacio_de_hierro_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Palacio de Hierro'),
        ),
        migrations.AlterField(
            model_name='place',
            name='reception_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del lugar de la recepción'),
        ),
    ]
