# Generated by Django 4.0.8 on 2023-01-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_alter_gifttable_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationbase',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='invitationbase',
            name='type_event',
            field=models.IntegerField(choices=[(None, '(Pendiente)'), (0, 'MIS XV'), (1, 'NUESTRA BODA'), (2, 'MI BAUTIZO')]),
        ),
    ]
