# Generated by Django 4.0.8 on 2023-01-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_alter_invitationbase_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='address_ceremony',
            new_name='ceremony_address',
        ),
    ]
