# Generated by Django 4.0.8 on 2023-02-05 01:40

from django.db import migrations, models
import django.db.models.deletion
import meetinginvite.invitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_rename_address_ceremony_place_ceremony_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_of_people', models.IntegerField(default=0)),
                ('save_the_date_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('save_the_date_opened', models.DateTimeField(blank=True, default=None, null=True)),
                ('invitation_code', models.CharField(db_index=True, default=meetinginvite.invitations.models._random_uuid, max_length=32, unique=True)),
                ('invitation_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('invitation_opened', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_invited', models.BooleanField(default=False)),
                ('is_attending', models.BooleanField(default=None, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('arrived', models.BooleanField(default=None, null=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitations.invitationbase')),
            ],
        ),
    ]
