# Generated by Django 4.0.8 on 2023-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0009_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='child',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='observations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='party',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
