# Generated by Django 4.0.8 on 2023-02-05 23:42

from django.db import migrations, models
import meetinginvite.invitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_party_adult_party_child_party_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='invitation_code',
            field=models.SlugField(blank=True, default=meetinginvite.invitations.models._random_uuid, max_length=255, unique=True, verbose_name='Party Slug'),
        ),
    ]
