version: '3'

volumes:
  meetinginvite_local_postgres_data: {}
  meetinginvite_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: meetinginvite_local_django
    container_name: meetinginvite_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: meetinginvite_production_postgres
    container_name: meetinginvite_local_postgres
    volumes:
      - meetinginvite_local_postgres_data:/var/lib/postgresql/data
      - meetinginvite_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: meetinginvite_local_docs
    container_name: meetinginvite_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./meetinginvite:/app/meetinginvite:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: meetinginvite_local_mailhog
    ports:
      - "8025:8025"

